import type { Metadata } from "next";
// import { Press_Start_2P } from "next/font/google";
import "./globals.css";

// const press_Start_2P = Press_Start_2P({
//   // subsets: ["cyrillic", "cyrillic-ext", "greek", "latin", "latin-ext"],
//   weight: "400",
//   preload: false,
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
